# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  # the theme to use by default in every presentation unless overridden.
  theme: catppuccin-macchiato-mika

  # the image protocol to use.
  image_protocol: iterm2
transition:
  # how long the transition should last.
  duration_millis: 200

  # how many frames should be rendered during the transition
  frames: 60

  # the animation to use
  animation:
    style: slide_horizontal
