[theme]
name = "kanagawa"

[colors]
# Successful commands timer + Stats (High)
AlertInfo = "#76946a"

# Current selection + Unsucessful commands timer + Stats (Low)
AlertError = "#e46876"

# Stats (Mid)
AlertWarn = "#ffa066"

# Full command + Keymaps + History count
Annotation = "#938aa9"

# Command list
Base = "#c8c093"

# Time elapsed since command
Guidance = "#7fb4ca"

# Stats (Count)
Muted = "#54546d"

# Doesn't look like it is used yet
Important = "#ff9e3b"

# Doesn't look like it is used yet
Title = "#6a9589"

# Full Palette

# fujiWhite     #dcd7ba;
# oldWhite      #c8c093;
# sumiInk0      #16161d;
# sumiInk1      #1f1f28;
# sumiInk2      #2a2a37;
# sumiInk3      #363646;
# sumiInk4      #54546d;
# waveBlue1     #223249;
# waveBlue2     #2d4f67;
# winterGreen   #2b3328;
# winterYellow  #49443c;
# winterRed     #43242b;
# winterBlue    #252535;
# autumnGreen   #76946a;
# autumnRed     #c34043;
# autumnYellow  #dca561;
# samuraiRed    #e82424;
# roninYellow   #ff9e3b;
# waveAqua1     #6a9589;
# dragonBlue    #658594;
# fujiGray      #727169;
# springViolet1 #938aa9;
# oniViolet     #957fb8;
# crystalBlue   #7e9cd8;
# springViolet2 #9cabca;
# springBlue    #7fb4ca;
# lightBlue     #a3d4d5;
# waveAqua2     #7aa89f;
# springGreen   #98bb6c;
# boatYellow1   #938056;
# boatYellow2   #c0a36e;
# carpYellow    #e6c384;
# sakuraPink    #d27e99;
# waveRed       #e46876;
# peachRed      #ff5d62;
# surimiOrange  #ffa066;
# katanaGray    #717c7c;
