# Drop this into ~/.config/atuin/themes/tokyo-night.toml, then reference it in atuin.conf
#
# See https://docs.atuin.sh/guide/theming/
[theme]
name = "tokyo-night"
parent = "default"

[colors]
AlertInfo = "#73daca"
AlertWarn = "#e0af68"
AlertError = "#f7768e"
Annotation = "#414868"
Base = "#a9b1d6"
Guidance = "#ff9e64"
Important = "#7aa2f7"
Title = "#bb9af7"
