# https://github.com/etrigan63/Catppuccin-starship/blob/main/user_starship.toml

# when displaying the nodejs version in the prompt, the initial call to node is
# slow. The subsequent calls are fast, so give the command a bit more time in
# the beginning.
#
# Using Node v22.13.0
# [WARN] - (starship::utils): Executing command "/Users/mikavilpas/.local/state/fnm_multishells/6152_1738395379087/bin/node" timed out.
# [WARN] - (starship::utils): You can set command_timeout in your config to a higher value to allow longer-running commands to keep executing.
command_timeout = 3000

palette = "catppuccin_mocha"
format = """
[](blue)\
$username\
[ ](fg:crust bg:blue)\
[](bg:text fg:blue)\
$directory\
[](fg:text bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:mauve)\
$nodejs\
$rust\
[](fg:mauve bg:teal)\
$aws\
$status\
[](fg:teal bg:blue)\
$time\
$cmd_duration\
[ ](fg:blue)\
\n$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "fg:crust bg:text"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:crust bg:peach"
format = '[[ $symbol $branch ](fg:crust bg:peach)]($style)'

[git_status]
style = "fg:crust bg:peach"
format = '[[($all_status$ahead_behind )](fg:crust bg:peach)]($style)'

[nodejs]
symbol = "󰎙"
style = "fg:crust bg:mauve"
format = '[[ $symbol ($version) ](fg:crust bg:mauve)]($style)'

[rust]
symbol = ""
style = "fg:crust bg:mauve"
format = '[[ $symbol ($version) ](fg:crust bg:mauve)]($style)'

[time]
disabled = false
time_format = "%R"                                 # Hour:Minute Format
style = "fg:crust bg:blue"
format = '[[ 󱑎 $time ](fg:crust bg:blue)]($style)'

[cmd_duration]
min_time = 500
# format = 'underwent [$duration](bold yellow)'
style = "fg:crust bg:blue"
format = '[[  $duration ](fg:crust bg:blue)]($style)'

[status]
style = 'fg:crust bg:green'
symbol = '🔴'
success_symbol = ''
format = '[ $symbol$signal_name$int]($style)'
map_symbol = true
disabled = false

[character]
format = "$symbol "
success_symbol = "\\$"

[aws]
format = '[$symbol$profile ]($style)'
style = 'fg:crust bg:green'
symbol = ' 󰸏 '
# [aws.profile_aliases]
# Enterprise_Naming_Scheme-voidstars = 'void**'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
