---
name: Test mise installation of "mika" tool
on:
  pull_request: ~
  push:
    branches:
      - main
  release:
    types: [published]
permissions:
  contents: read

jobs:
  test-mise-install:
    name: Test installing mika with mise
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install: false
          cache: false

      - name: Install mika with mise
        # note: the mise config in the repo might apply hooks
        run: mise install "github:mikavilpas/dotfiles@latest" --verbose

      - name: Verify mika is executable
        run: mise exec "github:mikavilpas/dotfiles@latest" -- mika --help
